default: &default
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000
  username: postgres
development:
  adapter: postgresql
  database: my_clipboard_database_development
  pool: 5
  timeout: 5000
  username: postgres
test:
  adapter: postgresql
  database: my_clipboard_database_test
  pool: 5
  timeout: 5000
  username: postgres
production:
  adapter: postgresql
  database: my_clipboard_database_production
  pool: 5
  timeout: 5000
  username: postgres